language: java
jdk: openjdk8
services:
  - xvfb
addons:
  chrome: stable
script: mvn test -B
deploy:
  provider: heroku
  api_key:
    secure: j3dIhzivuLw63KFH0/tl6nQcq1PVlvnksLAjh30p5rLqZafNsSn7qbeimWIK8w0jiuGY9txpfYmhga7WGMo17hc+I2BHUYHOXODM7+7vkFSZLGfxkkgB9ATLsYZtoMArEBs2CqIKUYnKEdJqq9cq/B5jhCpb5YcPcOSrqlsiFdttGEUATJtSGXTgWHoSJku1oltOF7bcbYbsxPIZsAPUG8SoyTXMkNRlrND4798FHnSOl0atMJf2oJfSZlXRsThpZsgVgsOBrGFYLg7N6KCbT5/vOtFdNrfGjuADKp/LgPAIJYKW/kvw4ysYuC022zXbz/RAoc+AECttC79VhqDUV+fpv6+udLvQWxVv80jpwIJ+o8IYYXas3SE15xiph8rgu34RpIkM4beLttfjAEB4dOY+xoymS9IVG1fUrXOHFN80B2vBAsl8m+aJAAvLw7R6+QuTDIHAOBeOiBKsC/OlAzbT/42usjm28QjYg4yaAVkTAWj2Dk5DNLWifXEmdWUkjztFhaoQY0uIcoolLKih4QMcccvAzT8FYLDo20rWq4S9x/d0Nq+GCRg0zvdLHGk85CQpDIUlTS023cyUKYtGCY9jJnsPkTyYmKnGrHBb71+SjnJjSgMVQbiGr7s9GA5d3Sv3rlDmkcMOSBx0MH0J+FD8OEEgw3NIUztRCYdDUQ4=
  app: periodicals-sb
