language: java
jdk: openjdk8
services:
  - postgresql
  - xvfb
before_script:
  - psql -c 'create database periodicals;' -U postgres
env:
  global:
  - PGPORT=5432
addons:
  chrome: stable
script: mvn test -B
