spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/periodicals
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        hbm2ddl:
          auto: validate
