spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/periodicals
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    initialization-mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        hbm2ddl:
          auto: create-drop
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

